<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\EmployeePerformance;
use App\Models\AuditLog;

class OrganizationAddonsSeeder extends Seeder
{
    public function run(): void
    {
        $users = User::all();
        $ceo = User::where('role', 'ceo')->first();
        
        $badges = ['Excellent', 'Good', 'Average', 'Need Review'];

        foreach ($users as $user) {
            // Seed Performance
            EmployeePerformance::create([
                'user_id' => $user->id,
                'reviewer_id' => $ceo ? $ceo->id : $user->id,
                'period_start' => now()->startOfYear(),
                'period_end' => now(),
                'score' => rand(60, 98),
                'badge' => $badges[array_rand($badges)],
                'notes' => 'Generated by demo seeder.'
            ]);

            // Seed Audit Log
            AuditLog::create([
                'user_id' => $ceo ? $ceo->id : $user->id,
                'target_user_id' => $user->id,
                'action' => 'account_created',
                'after_state' => $user->toArray(),
                'ip_address' => '127.0.0.1',
            ]);
        }
    }
}
