<?php

return [
    'core_dashboard' => [
        'label' => 'Dashboard Inti',
        'description' => 'Ringkasan perusahaan, profil, sesi, dan navigasi utama.',
        'category' => 'Fondasi',
        'default' => true,
        'available' => true,
        'locked' => true,
    ],
    'organization' => [
        'label' => 'Organisasi & Akun',
        'description' => 'Hirarki, anggota tim, jabatan kustom, dan pengajuan perubahan anggota.',
        'category' => 'Fondasi',
        'default' => true,
        'available' => true,
    ],
    'performance' => [
        'label' => 'Goal, KPI & Task',
        'description' => 'Goal divisi, rencana KPI, rules engine, task, bukti, dan verifikasi.',
        'category' => 'Kinerja',
        'default' => true,
        'available' => true,
    ],
    'approvals' => [
        'label' => 'Pusat Persetujuan',
        'description' => 'Approval bertingkat, riwayat keputusan, dan status pengajuan.',
        'category' => 'Kinerja',
        'default' => true,
        'available' => true,
    ],
    'attendance' => [
        'label' => 'Attendance',
        'description' => 'Clock in/out, live attendance, lokasi, dan statistik kehadiran.',
        'category' => 'SDM',
        'default' => true,
        'available' => true,
    ],
    'leave' => [
        'label' => 'Cuti',
        'description' => 'Pengajuan cuti staff/manager, persetujuan, dan tembusan HRD.',
        'category' => 'SDM',
        'default' => true,
        'available' => true,
    ],
    'resignation' => [
        'label' => 'Resign',
        'description' => 'Pengajuan resign berjenjang sampai CEO dengan tembusan HRD.',
        'category' => 'SDM',
        'default' => true,
        'available' => true,
    ],
    'hr_core' => [
        'label' => 'HRD Core',
        'description' => 'Dashboard HRD, profil karyawan, kontrak, dan administrasi SDM.',
        'category' => 'SDM',
        'default' => true,
        'available' => true,
    ],
    'chat' => [
        'label' => 'Internal Chat',
        'description' => 'Chat divisi, lampiran, dan pengumuman perusahaan.',
        'category' => 'Kolaborasi',
        'default' => true,
        'available' => true,
    ],
    'notifications' => [
        'label' => 'Notifikasi & Reminder',
        'description' => 'Notifikasi aktivitas, reminder deadline, dan escalation.',
        'category' => 'Kolaborasi',
        'default' => true,
        'available' => true,
    ],
    'crm' => [
        'label' => 'CRM & Leads',
        'description' => 'Pipeline prospek, kanban leads, dan pemantauan konversi.',
        'category' => 'Komersial',
        'default' => true,
        'available' => true,
    ],
    'finance' => [
        'label' => 'Finance & Cashflow',
        'description' => 'Pemasukan klien, termin, invoice, ekspor, dan pemantauan cashflow.',
        'category' => 'Keuangan',
        'default' => true,
        'available' => true,
    ],
    'backup' => [
        'label' => 'Backup Mandiri',
        'description' => 'Unduhan data sesuai kewenangan masing-masing akun.',
        'category' => 'Keamanan',
        'default' => true,
        'available' => true,
    ],
    'gemini' => [
        'label' => 'Gemini Copilot',
        'description' => 'Copilot dengan API key pribadi dan konteks sesuai kewenangan.',
        'category' => 'AI & Analitik',
        'default' => true,
        'available' => true,
    ],
    'accounting' => [
        'label' => 'Akuntansi Double-Entry',
        'description' => 'Jurnal berpasangan, chart of accounts, laba rugi bulanan, dan evaluasi tahunan otomatis.',
        'category' => 'ERP Suba Arch',
        'default' => true,
        'available' => true,
    ],
    'payroll' => [
        'label' => 'Payroll Indonesia',
        'description' => 'Gaji, lembur, BPJS, PPh 21, benefit, dan slip gaji aman.',
        'category' => 'Roadmap ERP',
        'default' => false,
        'available' => false,
    ],
    'project_costing' => [
        'label' => 'Project Costing',
        'description' => 'Anggaran, biaya aktual, progres, dan margin untuk proyek desain maupun kontraktor.',
        'category' => 'ERP Suba Arch',
        'default' => true,
        'available' => true,
    ],
    'procurement' => [
        'label' => 'Procurement',
        'description' => 'Vendor, purchase request, RFQ, PO, penerimaan, dan invoice matching.',
        'category' => 'Roadmap ERP',
        'default' => false,
        'available' => false,
    ],
    'inventory' => [
        'label' => 'Supply Chain & Inventory',
        'description' => 'Produk, multi-gudang, stok, serial/lot, reorder, dan valuasi.',
        'category' => 'Roadmap ERP',
        'default' => false,
        'available' => false,
    ],
    'document_management' => [
        'label' => 'Dokumen & E-Sign',
        'description' => 'Penerbitan sertifikat magang, persetujuan internal, hash integritas, dan verifikasi publik.',
        'category' => 'ERP Suba Arch',
        'default' => true,
        'available' => true,
    ],
    'client_portal' => [
        'label' => 'Client & Vendor Portal',
        'description' => 'Portal eksternal terbatas untuk progres, dokumen, invoice, dan komunikasi.',
        'category' => 'Roadmap ERP',
        'default' => false,
        'available' => false,
    ],
    'talent_management' => [
        'label' => 'Talent Management',
        'description' => 'Review kinerja, potensi, kompetensi, rencana pengembangan, dan kesiapan peran.',
        'category' => 'ERP Suba Arch',
        'default' => true,
        'available' => true,
    ],
    'advanced_analytics' => [
        'label' => 'Advanced Analytics',
        'description' => 'Analitik lintas SDM, task, attendance, proyek, keuangan, dan peringatan risiko.',
        'category' => 'ERP Suba Arch',
        'default' => true,
        'available' => true,
    ],
];
